#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Fonts */
// Masion-Neue-Book
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_14);


// Middle (Typically 480x480)
LV_IMG_DECLARE(esp_brookesia_image_middle_app_launcher_default_112_112);
LV_IMG_DECLARE(esp_brookesia_image_middle_navigation_bar_back_32_32);
LV_IMG_DECLARE(esp_brookesia_image_middle_navigation_bar_home_32_32);
LV_IMG_DECLARE(esp_brookesia_image_middle_navigation_bar_recents_screen_32_32);
LV_IMG_DECLARE(esp_brookesia_image_middle_recents_screen_trash_48_48);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_battery_charge_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_battery_level1_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_battery_level2_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_battery_level3_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_battery_level4_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_wifi_close_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_wifi_level1_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_wifi_level2_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_wifi_level3_24_24);

#ifdef __cplusplus
}
#endif
